apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo
    app.kubernetes.io/instance: demo-app
  name: demo-deployment
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: ghcr.io/nirmata/demo-argocd:v1
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
      volumes:
      - name: cache-volume
        emptyDir:
          sizeLimit: 500Mi
