apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo
    app.kubernetes.io/instance: demo-app
  name: demo-deployment
  namespace: demo
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
      annotations:
        vig.cz/duck: foo
    spec:
      containers:
      - name: demo
        image: nginx:1.27.0-alpine3.19
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
      volumes:
      - name: cache-volume
        emptyDir:
          sizeLimit: 500Mi
