apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-default-securitycontext
  annotations:
    policies.kyverno.io/title: Add Default securityContext
    policies.kyverno.io/category: PSS
    policies.kyverno.io/subject: Deployment
    policies.kyverno.io/description: >-
      This policy will mutate a Deployment to set a restricted securityContext 
      for the pod and containers if they are not already set.
spec:
  rules:
    - name: add-securitycontext
      match:
        resources:
          kinds:
            - Pod
      mutate:
        patchStrategicMerge:
          spec:
            securityContext:
              +(runAsNonRoot): true
              +(runAsUser): 1000
              +(runAsGroup): 3000
              +(fsGroup): 2000