apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-securitycontext
  annotations:
    policies.kyverno.io/title: Add restricted securityContext
    policies.kyverno.io/category: PSS
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      This policy will mutate a pod to set a restricted securityContext 
spec:
  rules:
    - name: add-securitycontext
      match:
        resources:
          kinds:
            - Pod
      mutate:
        patchStrategicMerge:
          spec:
            securityContext:
              +(runAsNonRoot): true
              +(runAsUser): 1000
              +(runAsGroup): 3000
              +(fsGroup): 2000