apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: service-account
  annotations:
    policies.kyverno.io/title: Disable Automount Service Account
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      This policy will disable automount of Kubernetes service accounts 
spec:
  rules:
    - name: disable-automount
      match:
        resources:
          kinds:
            - Pod
      mutate:
        patchStrategicMerge:
          spec:
            +(automountServiceAccountToken): false
